package com.mkring.james.chatbackend.rocketchat

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

// generated by http://www.jsonschema2pojo.org/
class AvailableStreamsAnswer {
    @SerializedName("id")
    @Expose
    var id: String? = null
    @SerializedName("msg")
    @Expose
    var msg: String? = null
    @SerializedName("result")
    @Expose
    var result: List<Result>? = null

    override fun toString(): String {
        return "AvailableStreamsAnswer(id=$id, msg=$msg, result=$result)"
    }

}

class Result {
    @SerializedName("t")
    @Expose
    var t: String? = null
    @SerializedName("unread")
    @Expose
    var unread: Int? = null
    @SerializedName("open")
    @Expose
    var open: Boolean? = null
    @SerializedName("name")
    @Expose
    var name: String? = null
    @SerializedName("_id")
    @Expose
    var id: String? = null
    @SerializedName("u")
    @Expose
    var u: U? = null
    @SerializedName("rid")
    @Expose
    var rid: String? = null
    @SerializedName("_updatedAt")
    @Expose
    var updatedAt: UpdatedAt? = null
    @SerializedName("ts")
    @Expose
    var ts: Ts? = null
    @SerializedName("alert")
    @Expose
    var alert: Boolean? = null

    override fun toString(): String {
        return "Result(t=$t, unread=$unread, open=$open, name=$name, id=$id, u=$u, rid=$rid, updatedAt=$updatedAt, ts=$ts, alert=$alert)"
    }

}

class Ts {
    @SerializedName("\$date")
    @Expose
    var `$date`: Long? = null

    override fun toString(): String {
        return "Ts(`date`=$`$date`)"
    }

}

class U {
    @SerializedName("username")
    @Expose
    var username: String? = null
    @SerializedName("_id")
    @Expose
    var id: String? = null

    override fun toString(): String {
        return "U(username=$username, id=$id)"
    }

}

class UpdatedAt {
    @SerializedName("\$date")
    @Expose
    var `$date`: Long? = null

    override fun toString(): String {
        return "UpdatedAt(`date`=$`$date`)"
    }

}